# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

compiler: gcc

# Cache can be cleared from the travis settings menu, see docs currently at
# https://docs.travis-ci.com/user/caching#Clearing-Caches
cache:
  - ccache

os:
    - linux

dist: xenial

sudo: true

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.7
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - MAIN_CMD='python setup.py'
        # Add the current dev version of astropy-healpix waiting for the
        # new release to support Python 3.7.
        # Cython is necessary for pip installing the dev version of astropy-healpix.
        - PIP_DEPENDENCIES='Cython astropy-healpix networkx spherical-geometry'
        - CONDA_DEPENDENCIES='Cython shapely pytest-arraydiff'
        - CONDA_CHANNELS='astropy'
        - SETUP_XVFB=True
        - ASTROPY_USE_SYSTEM_PYTEST=1

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'

matrix:
    include:

        # Do a coverage test in Python 3.7
        - env: SETUP_CMD='test --coverage'
               CONDA_CHANNELS='conda-forge astropy'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - env: PYTHON_VERSION=2.7
               SETUP_CMD='build_docs -w'
        - env: PYTHON_VERSION=3.6
               SETUP_CMD='build_docs -w'
               CONDA_CHANNELS='conda-forge astropy'

        # Do a test without the optional dependencies
        - env: SETUP_CMD='test'
               CONDA_DEPENDENCIES='Cython pytest-arraydiff'


        # Try Astropy development version
        - env: ASTROPY_VERSION=development
               CONDA_CHANNELS='conda-forge astropy'

        # Try older numpy versions
        - env: PYTHON_VERSION=3.6
               NUMPY_VERSION=1.11
        - env: PYTHON_VERSION=3.5
               NUMPY_VERSION=1.10
               ASTROPY_VERSION=3.0

        # Try numpy pre-release
        - env: NUMPY_VERSION=prerelease

        # Do a PEP8 test with pycodestyle
        - env: MAIN_CMD='pycodestyle regions --count' SETUP_CMD=''

        # Try MacOS X
        - os: osx
          env: SETUP_CMD='test'

install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='regions/tests/coveragerc'; fi
